### ISSUE TITLE
Failed to load the atom-vlc package

### ISSUE THREAD

**Issue by egordorichev** [renatoalencar/atom-vlc#1]
Hello! I tryed to instal your package and got a error from Atom:

**Atom Version**: 1.7.2
**System**: linux 3.18.9-gentoo
**Thrown From**: [atom-vlc](https://github.com/renatoalencar/atom-vlc) package, v0.2.1
### Stack Trace

Failed to load the atom-vlc package

```
At '../node_modules/font-awesome/less/font-awesome.less' wasn't found in /home/egor/.atom/packages/atom-vlc/styles/atom-vlc.less:6:0

LessError: '../node_modules/font-awesome/less/font-awesome.less' wasn't found
  at /home/egor/.atom/packages/atom-vlc/styles/atom-vlc.less:6:0
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
monokai, v0.18.0

# Dev
No dev packages
```

Thank you, Egor.

**Comment by renatoalencar** [comment]
Hello dude, thanks for report. 

Did you install the package from `apm` or clone and link the GitHub repo?

If you did the second, try to run `npm install` inside the package directory.

**Comment by egordorichev** [comment]
Thank you for your reply! I used `apm` manager.

**Comment by renatoalencar** [comment]
I saw that package dependencies was in devDependencies. I will fix it, and publish soon. 

Thanks.
